### PR TITLE
#165363878 Implementing feedback from LFA

### PR DESCRIPTION
**Pull request by okezieobi**
**What this PR does ?**
1) Updates UI templates to follow standard layout format
2) Refractor Controllers
3) Fix failling tests
4) Remove dist folder

**Description of task completed so far?**
1)Updated UI templates
2)Fixed failing tests and deleted dist folder

**How to test this ?**
A) To start viewing user side UI templates click on `index.html` and to view admin/staff templates click on `UI/Admin_Staff/admin_staff_signin.html`
B) To test endpoints, clone repo, icd into it, install dependencies and run `npm test`.
3) Finished phase of refactoring my controllers by moving a majority of the `if` statements out of the controllers

**Relevant Pivotal story**
#165363878

### CODE REVIEW

**Comment by samdiano** [comment]
look into your build that's failing

**Comment by samdiano** [comment]
why is your build failing?

**Comment by okezieobi** [comment]
> why is your build failing?

A few tests are failing, like 4 out of 94, I checked and saw they are logical errors with at most 2 of my controllers. I will fixed them as soon as I am done with writing my 2 blogs.

**Comment by samdiano** [comment]
alright

**Comment by okezieobi** [comment]
I have fixed the failing tests and deleted the dist folder as recommended

**Pull request merged**
